version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - /var/lib/data/zk-data:/opt/zookeeper-3.4.13/data
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT 
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/lib/data/kafka-data/node1:/kafka
    depends_on:
      - zookeeper
  consumer:
    build: ./consumer
    container_name: consumer
    ports:
      - "5050:5050"
    volumes:
      - ./consumer:/usr/src/app
    depends_on:
      - kafka
  producer:
    build: ./producer
    container_name: producer
    volumes:
      - ./producer:/usr/src/app
    depends_on:
      - kafka